name = "financeiro-fazendalageado"
main = "src/index.ts"
compatibility_date = "2024-02-06"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "financeiro_db"
database_id = "4172e157-80f8-4994-af1a-5c139d0b6389"

[triggers]
crons = ["0 6 1 * *"]  # Executa todo dia 1 do mês às 6h da manhã 