/** Minimal OFX snippets for unit tests */

export const OFX_CAIXA_MARCO = `
<OFX>
 <BANKMSGSRSV1>
  <STMTTRNRS>
   <STMTRS>
    <BANKACCTFROM>
     <BANKID>0104</BANKID>
     <ACCTID>0005848812752</ACCTID>
    </BANKACCTFROM>
    <BANKTRANLIST>
     <STMTTRN>
      <TRNTYPE>DEBIT</TRNTYPE>
      <DTPOSTED>2026031000[-3:BRT]</DTPOSTED>
      <TRNAMT>-1.061.52</TRNAMT>
      <FITID>374751</FITID>
      <CHECKNUM>374751</CHECKNUM>
      <MEMO>CONSORCIO</MEMO>
     </STMTTRN>
     <STMTTRN>
      <TRNTYPE>DEBIT</TRNTYPE>
      <DTPOSTED>2026030200[-3:BRT]</DTPOSTED>
      <TRNAMT>-114.35</TRNAMT>
      <FITID>369639</FITID>
      <CHECKNUM>369639</CHECKNUM>
      <MEMO>DEBITO CAPITALIZACAO</MEMO>
     </STMTTRN>
    </BANKTRANLIST>
   </STMTRS>
  </STMTTRNRS>
 </BANKMSGSRSV1>
</OFX>`;

export const OFX_STANDARD_BANK = `
<OFX>
 <BANKMSGSRSV1>
  <STMTTRNRS>
   <STMTRS>
    <BANKACCTFROM>
     <BANKID>341</BANKID>
    </BANKACCTFROM>
    <BANKTRANLIST>
     <STMTTRN>
      <DTPOSTED>20260115000000</DTPOSTED>
      <TRNAMT>-500.00</TRNAMT>
      <FITID>std-001</FITID>
      <MEMO>PAGAMENTO FORNECEDOR</MEMO>
     </STMTTRN>
     <STMTTRN>
      <DTPOSTED>20260120000000</DTPOSTED>
      <TRNAMT>1500.25</TRNAMT>
      <FITID>std-002</FITID>
      <MEMO>RECEBIMENTO CLIENTE</MEMO>
     </STMTTRN>
     <STMTTRN>
      <DTPOSTED>20260125000000</DTPOSTED>
      <TRNAMT>-1234567.89</TRNAMT>
      <FITID>std-003</FITID>
      <MEMO>TRANSFERENCIA GRANDE</MEMO>
     </STMTTRN>
    </BANKTRANLIST>
   </STMTRS>
  </STMTTRNRS>
 </BANKMSGSRSV1>
</OFX>`;

export const OFX_WITH_IGNORED = `
<OFX>
 <BANKMSGSRSV1>
  <STMTTRNRS>
   <STMTRS>
    <BANKACCTFROM><BANKID>999</BANKID></BANKACCTFROM>
    <BANKTRANLIST>
     <STMTTRN>
      <DTPOSTED>20260101000000</DTPOSTED>
      <TRNAMT>-100.00</TRNAMT>
      <FITID>valid-1</FITID>
      <MEMO>LANCAMENTO VALIDO</MEMO>
     </STMTTRN>
     <STMTTRN>
      <DTPOSTED>20260102000000</DTPOSTED>
      <TRNAMT>-50.00</TRNAMT>
      <FITID>blocked-1</FITID>
      <MEMO>Depósito bloqueado</MEMO>
     </STMTTRN>
     <STMTTRN>
      <DTPOSTED>20260103000000</DTPOSTED>
      <TRNAMT>-25.00</TRNAMT>
      <FITID>blocked-2</FITID>
      <MEMO>Movimento do dia</MEMO>
     </STMTTRN>
     <STMTTRN>
      <DTPOSTED>20260104000000</DTPOSTED>
      <TRNAMT>invalid</TRNAMT>
      <FITID>invalid-amt</FITID>
      <MEMO>VALOR INVALIDO</MEMO>
     </STMTTRN>
     <STMTTRN>
      <DTPOSTED>20260105000000</DTPOSTED>
      <TRNAMT>-75.00</TRNAMT>
      <MEMO>SEM FITID</MEMO>
     </STMTTRN>
    </BANKTRANLIST>
   </STMTRS>
  </STMTTRNRS>
 </BANKMSGSRSV1>
</OFX>`;

export const OFX_BB_CONS_GROUP = `
<OFX>
 <BANKMSGSRSV1>
  <STMTTRNRS>
   <STMTRS>
    <BANKACCTFROM><BANKID>1</BANKID></BANKACCTFROM>
    <BANKTRANLIST>
     <STMTTRN>
      <DTPOSTED>20260110000000</DTPOSTED>
      <TRNAMT>-100.00</TRNAMT>
      <FITID>bb-1</FITID>
      <REFNUM>REF-ABC</REFNUM>
      <MEMO>BB CONS PARCELA 1</MEMO>
     </STMTTRN>
     <STMTTRN>
      <DTPOSTED>20260110000000</DTPOSTED>
      <TRNAMT>-50.00</TRNAMT>
      <FITID>bb-2</FITID>
      <REFNUM>REF-ABC</REFNUM>
      <MEMO>BB CONS PARCELA 2</MEMO>
     </STMTTRN>
    </BANKTRANLIST>
   </STMTRS>
  </STMTTRNRS>
 </BANKMSGSRSV1>
</OFX>`;
